version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=report_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./media:/app/media  # Для хранения картинок и PDF локально пока нет S3
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/report_app
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=diplom-media
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_PUBLIC_ENDPOINT_URL=http://localhost:9000
      - USE_S3=True
    depends_on:
      db:
        condition: service_healthy  # Теперь бэк ждет БД
      redis:
        condition: service_started

  worker:
    build: ./backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
      - ./media:/app/media
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/report_app
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=diplom-media
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_PUBLIC_ENDPOINT_URL=http://localhost:9000
      - USE_S3=True
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb -p local/diplom-media || true;
      mc anonymous set download local/diplom-media;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data: