# Generated by Django 4.2.7 on 2026-05-20 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('course_name', models.CharField(blank=True, max_length=255, verbose_name='Дисциплина')),
                ('lab_number', models.IntegerField(default=1, verbose_name='Номер работы')),
                ('record_book_number', models.CharField(blank=True, max_length=50, verbose_name='№ зачетки')),
                ('content_json', models.JSONField(default=list, verbose_name='Структура блоков')),
                ('raw_latex', models.TextField(blank=True, verbose_name='Сгенерированный код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
