# Generated by Django 4.2.7 on 2026-05-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='record_book_number',
        ),
        migrations.AddField(
            model_name='document',
            name='chair_head_initials',
            field=models.CharField(default='И. И.', max_length=10, verbose_name='Инициалы зав. каф.'),
        ),
        migrations.AddField(
            model_name='document',
            name='chair_head_surname',
            field=models.CharField(default='Иванов', max_length=100, verbose_name='Фамилия зав. каф.'),
        ),
        migrations.AddField(
            model_name='document',
            name='chair_name',
            field=models.CharField(default='«ПРИКЛАДНАЯ ИТ»', max_length=255, verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='document',
            name='controller_degree',
            field=models.CharField(default='канд. техн. наук, доцент', max_length=255, verbose_name='Степень н/контр.'),
        ),
        migrations.AddField(
            model_name='document',
            name='controller_initials',
            field=models.CharField(default='А. А.', max_length=10, verbose_name='Инициалы н/контр.'),
        ),
        migrations.AddField(
            model_name='document',
            name='controller_surname',
            field=models.CharField(default='Петров', max_length=100, verbose_name='Фамилия н/контр.'),
        ),
        migrations.AddField(
            model_name='document',
            name='direction_code',
            field=models.CharField(default='09.03.04', max_length=50, verbose_name='Код направления'),
        ),
        migrations.AddField(
            model_name='document',
            name='direction_name',
            field=models.CharField(default='Программная инженерия', max_length=255, verbose_name='Название направления'),
        ),
        migrations.AddField(
            model_name='document',
            name='institute_name',
            field=models.CharField(default='ИНСТИТУТ КОСМИЧЕСКИХ И ИНФОРМАЦИОННЫХ ТЕХНОЛОГИЙ', max_length=255, verbose_name='Институт'),
        ),
        migrations.AddField(
            model_name='document',
            name='supervisor_degree',
            field=models.CharField(blank=True, max_length=255, verbose_name='Степень рук.'),
        ),
        migrations.AddField(
            model_name='document',
            name='supervisor_initials',
            field=models.CharField(blank=True, max_length=10, verbose_name='Инициалы рук.'),
        ),
        migrations.AddField(
            model_name='document',
            name='supervisor_surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия рук.'),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='document',
            name='raw_latex',
            field=models.TextField(blank=True, verbose_name='RAW код с маркерами'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Тема работы'),
        ),
    ]
