# Generated by Django 4.2.7 on 2026-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='compilation_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='compilation_status',
            field=models.CharField(choices=[('IDLE', 'Ожидает компиляции'), ('PENDING', 'В очереди'), ('RUNNING', 'Компилируется'), ('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка')], default='IDLE', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='compilation_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='compiled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
