# Generated by Django 4.2.7 on 2026-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_card',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер зачетки'),
        ),
    ]
